//PRODUCT LIST
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAILED = 'PRODUCT_LIST_FAILED'

//SINGLE PRODUCTS
export const PRODUCT_REQUEST = 'PRODUCT_REQUEST';
export const PRODUCT_FAILED = 'PRODUCT_FAILED';
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';

//CART
export const CART_REMOVE = 'CART_REMOVE';
export const CART_ADD = 'CART_ADD';

//CHECKOUT
export const ADD_TO_CHECKOUT = 'ADD_TO_CHECKOUT';
export const REMOVE_TO_CHECKOUT = 'REMOVE_TO_CHECKOUT';
